version: '2'
services:

  envoy:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  crud:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./crud-envoy.yaml:/etc/crud-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - crud
    environment:
      - SERVICE_NAME=crud
    expose:
      - "80"

networks:
  envoymesh: {}
